const Menu = [
  {
    id: 1,
    item: "Chicken Gravy",
    image: "Images/Chicken_Gravy.jpg",
    category: "Dinner",
    price: 99,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 2,
    item: "Idli",
    image: "Images/Idli.jpg",
    category: "Breakfast",
    price: 69,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 3,
    item: "French Fries",
    image: "Images/French_Fries.jpg",
    category: "Snacks",
    price: 49,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 4,
    item: "Dosa",
    image: "Images/Dosa.jpg",
    category: "Breakfast",
    price: 119,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 5,
    item: "Chapati",
    image: "Images/Chapati.jpg",
    category: "Dinner",
    price: 59,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 6,
    item: "Full Meals",
    image: "Images/Full_Meals.jpg",
    category: "Lunch",
    price: 199,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 7,
    item: "Veg-Samosa",
    image: "Images/Veg_Samosa.jpg",
    category: "Snacks",
    price: 29,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 8,
    item: "Biryani",
    image: "Images/Biryani.jpg",
    category: "Lunch",
    price: 249,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 9,
    item: "Pizza",
    image: "Images/Pizza.jpg",
    category: "Snacks",
    price: 179,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 10,
    item: "Fudge Cake",
    image: "Images/Fudge_Cake.jpg",
    category: "Cakes",
    price: 119,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 11,
    item: "Burger",
    image: "Images/Burger.jfif",
    category: "Snacks",
    price: 89,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 12,
    item: "Strawberry Cake",
    image: "Images/Strawberry_Cake.jpg",
    category: "Cakes",
    price: 119,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 13,
    item: "Fried Rice",
    image: "Images/Fried_Rice.jpg",
    category: "Chinese",
    price: 89,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
  {
    id: 14,
    item: "Noodles",
    image: "Images/Noodles.jpg",
    category: "Chinese",
    price: 79,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ...",
  },
];

export default Menu;
